services:
    keycloak:
        image: quay.io/keycloak/keycloak:26.0.5
        container_name: keycloak-nerus
        ports:
            - 18080:8080
        environment:
            - KC_BOOTSTRAP_ADMIN_USERNAME=admin
            - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
            # - KC_DB=mssql
            # - KC_DB_URL_HOST=mssql
            # - KC_DB_URL_PORT=${DB_PORT}
            # - KC_DB_URL_DATABASE=${DB_DATABASE}
            # - KC_DB_SCHEMA=keycloak
            # - KC_DB_USERNAME=${DB_USER}
            # - KC_DB_PASSWORD=${DB_ROOT_PASSWORD}
            # - KC_TRANSACTION-XA-ENABLED=true
        volumes:
            - ./.containers/keycloak/data:/opt/keycloak/data
            - ./.containers/keycloak/themes:/opt/keycloak/themes
        command: ["start-dev"]
        networks:
            - local

networks:
    local: