# docker run -p 8080:8080 -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin  start-dev[]
services:
    keycloak:
        image: quay.io/keycloak/keycloak:26.0.5
        container_name: keycloak-nerus
        ports:
            - 18080:8080
        environment:
            - KC_BOOTSTRAP_ADMIN_USERNAME:admin
            - KC_BOOTSTRAP_ADMIN_PASSWORD:admin
        volumes:
            - ./.containers/keycloak/data:/opt/keycloak/data
            - ./.containers/keycloak/themes:/opt/keycloak/themes
        command: ["start-dev"]
        # depends_on:
        #     - postgres

    # postgres:
    #   image: postgres:latest
    #   container_name: keycloak_postgres
    #   volumes:
    #     - ./postgres_data:/var/lib/postgresql/data
    #   environment:
    #     POSTGRES_DB: keycloak
    #     POSTGRES_USER: keycloak
    #     POSTGRES_PASSWORD: password

# volumes:
#   postgres_data:
#       driver: local